[phases.setup]
nixPkgs = ["...", "coreutils", "python3", "python3Packages.pip"]

[phases.install]
cmds = ["...", "python3 -m venv /app/.venv", "/app/.venv/bin/pip install --no-cache-dir -r python/requirements.txt"]

[variables]
NIXPACKS_NODE_VERSION = "22"
